# Generated by Django 3.2.8 on 2021-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('category', models.TextField(choices=[('Dev', 'Dev'), ('DevOps', 'DevOps'), ('Feel Good', 'Feel Good'), ('BIM', 'BIM'), ('Makers', 'Makers'), ('Agile', 'Agile'), ('UX/UI', 'UX/UI'), ('Data', 'Data'), ('SSI', 'SSI'), ('Industrie', 'Industrie')], verbose_name='Category')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(default='background-image.png', upload_to='')),
            ],
        ),
    ]
